<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/style.css">
        <script src="utilities/utilities.js"></script>
        <title>starter project</title>
        <link rel="stylesheet" href="css/main.css">
    </head>
    <body>

        <h1>Starter Project</h1>
        <script src="js/main.js"></script>
    </body>
</html>
